# Generated by Django 3.1.3 on 2021-03-26 01:18

from django.db import migrations, models
import login_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usr_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(max_length=20, unique=True, verbose_name='用户id')),
                ('usr_email', models.CharField(max_length=40, null=True, unique=True, verbose_name='用户邮箱')),
                ('usr_pwd', models.CharField(max_length=20, verbose_name='用户密码')),
                ('usr_nkname', models.CharField(max_length=40, null=True, verbose_name='用户昵称')),
                ('usr_pic', models.ImageField(blank=True, null=True, upload_to=login_module.models.user_directory_path, verbose_name='照片')),
            ],
        ),
    ]
