# Generated by Django 3.1.3 on 2021-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_info',
            name='usr_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='usr_info',
            name='usr_pwd',
            field=models.CharField(max_length=256, verbose_name='用户密码'),
        ),
    ]
