# Generated by Django 3.1.7 on 2021-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_info',
            name='recommend_user',
            field=models.CharField(max_length=20, verbose_name='推荐用户'),
        ),
    ]
