# Generated by Django 3.1.7 on 2021-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0002_auto_20210417_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_pic',
            name='picture_key',
            field=models.CharField(max_length=20, verbose_name='图片对应推荐编号'),
        ),
    ]
