# Generated by Django 3.1.3 on 2021-06-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0006_auto_20210527_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend_info',
            name='recommend_flag',
        ),
    ]
