from login_test import *
from selenium.webdriver.common.keys import Keys

elem = browser.find_element_by_id("navbarDropdown")
ActionChains(browser).move_to_element(elem).click(elem).perform()
time.sleep(2)
elem = browser.find_element_by_link_text("提交测评")
ActionChains(browser).move_to_element(elem).click(elem).perform()
elem = browser.find_element_by_id("dropdownMenuButton")
ActionChains(browser).move_to_element(elem).click(elem).perform()
elem = browser.find_element_by_link_text("正餐")
ActionChains(browser).move_to_element(elem).click(elem).perform()
time.sleep(2)
elem = browser.find_element_by_css_selector(".dropdown > .show > div > button")
ActionChains(browser).move_to_element(elem).click(elem).perform()
time.sleep(2)
elem = browser.find_element_by_id("title")
elem.send_keys("selenium test")
elem = browser.find_element_by_id("editor")
elem.send_keys("editor")
elem = browser.find_element_by_css_selector("#pic_div > .form-control")
elem.send_keys("D:\\unicornt\\图片\\2019-09\\IMG_0010.JPG")
time.sleep(2)
elem = browser.find_element_by_css_selector("form > p > input")
elem.click()